import flags
import numpy
from numpy.typing import NDArray
# from numpy.typing import flags
from typing import overload


class ImplicitMPC(MPCBase):
    def __init__(self, num_statessss: int, num_inputs: int, len_horizon: int,
                 num_control_points: int, use_input_cost: bool=False,
                 use_slew_rate: bool=False, saturate_states: bool=False) -> None: ...
    @overload
    def getInputTrajectory(self, u_traj: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def getInputTrajectory(self) -> NDArray[numpy.float64]: ...
    @overload
    def getPredictedStateTrajectory(self, x_traj: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def getPredictedStateTrajectory(self) -> NDArray[numpy.float64]: ...
    def setInputLimits(self, u_min: NDArray[numpy.float64], u_max: NDArray[numpy.float64]) -> None: ...
    def setSlewRate(self, u_slew: NDArray[numpy.float64]) -> None: ...
    def setStateLimits(self, x_min: NDArray[numpy.float64], x_max: NDArray[numpy.float64]) -> None: ...


class MPCBase:
    def __init__(self, num_states: int, num_inputs: int, len_horizon: int, num_control_points: int, use_input_cost: bool=False, use_slew_rate: bool=False, saturate_states: bool=False) -> None: ...
    @overload
    def getInputTrajectory(self, u_traj: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def getInputTrajectory(self) -> NDArray[numpy.float64]: ...
    @overload
    def getNextInput(self, u0: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def getNextInput(self) -> NDArray[numpy.float64]: ...
    @overload
    def getParameterizedInputTrajectory(self, u_traj_ctrl_pts: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def getParameterizedInputTrajectory(self) -> NDArray[numpy.float64]: ...
    @overload
    def getPredictedStateTrajectory(self, x_traj: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def getPredictedStateTrajectory(self) -> NDArray[numpy.float64]: ...
    def initializeSolver(self, solver_settings: OSQPSettings = ...) -> bool: ...
    @overload
    def propagateModel(self, x: NDArray[numpy.float64], u: NDArray[numpy.float64], x_next: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    @overload
    def propagateModel(self, x: NDArray[numpy.float64], u: NDArray[numpy.float64]) -> NDArray[numpy.float64]: ...
    def setInputLimits(self, u_min: NDArray[numpy.float64], u_max: NDArray[numpy.float64]) -> None: ...
    def setInputWeights(self, R_diag: NDArray[numpy.float64]) -> None: ...
    def setModelContinuous2Discrete(self, Ac: NDArray[numpy.float64], Bc: NDArray[numpy.float64], wc: NDArray[numpy.float64], dt: float, tol: float = ...) -> None: ...
    def setModelDiscrete(self, Ad: NDArray[numpy.float64], Bd: NDArray[numpy.float64], wd: NDArray[numpy.float64]) -> None: ...
    def setReferenceInput(self, u_step: NDArray[numpy.float64]) -> None: ...
    def setReferenceParameterizedInputTrajectory(self, u_traj_ctrl_pts: NDArray[numpy.float64]) -> None: ...
    def setReferenceState(self, x_step: NDArray[numpy.float64]) -> None: ...
    def setReferenceStateTrajectory(self, x_traj: NDArray[numpy.float64]) -> None: ...
    def setSlewRate(self, u_slew: NDArray[numpy.float64]) -> None: ...
    def setStateLimits(self, x_min: NDArray[numpy.float64], x_max: NDArray[numpy.float64]) -> None: ...
    def setStateWeights(self, Q_diag: NDArray[numpy.float64]) -> None: ...
    def setStateWeightsTerminal(self, Qf_diag: NDArray[numpy.float64]) -> None: ...
    def setWeights(self, Q_diag: NDArray[numpy.float64], R_diag: NDArray[numpy.float64]) -> None: ...
    def solve(self, x0: NDArray[numpy.float64]) -> bool: ...
    @property
    def len_horizon(self) -> int: ...
    @property
    def num_ctrl_pts(self) -> int: ...
    @property
    def num_inputs(self) -> int: ...
    @property
    def num_states(self) -> int: ...


class MPCLogger:
    def __init__(self, mpc: MPCBase, save_location: str='/tmp/mpc_data') -> None: ...
    def logPreviousSolve(self, t0: float, ts: float, x0: NDArray[numpy.float64], solve_time: float=-1, write_every: int=1) -> None: ...
    def writeParamFile(self, filename: str = ...) -> None: ...


class OSQPSettings:
    adaptive_rho: int
    adaptive_rho_fraction: float
    adaptive_rho_interval: int
    adaptive_rho_tolerance: float
    alpha: float
    check_termination: int
    delta: float
    eps_abs: float
    eps_dual_inf: float
    eps_prim_inf: float
    eps_rel: float
    linsys_solver: linsys_solver_type
    max_iter: int
    polish: int
    polish_refine_iter: int
    rho: float
    scaled_termination: int
    scaling: int
    sigma: float
    time_limit: float
    verbose: int
    warm_start: int
    def __init__(self) -> None: ...
